name: Github Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: "go.mod"

      - name: Lint
        run: make lint

  build:
    name: go Test
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: "go.mod"

      - name: Test
        run: make test

      - name: Send coverage
        uses: shogo82148/actions-goveralls@9606dbc5ac5cf888a0e9ef901515c3cd516a2790 # v1.11.0
        with:
          path-to-profile: coverage.out

  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: 🕹️ Install kind with registry
        uses: bakito/kind-with-registry-action@9c031e8b0c6f20fec65ca5a58901d05e585ff5d0 # v1.0.0
        with:
          kind_cluster_name: e2e

      - name: 🖼️ Build image
        run: ./testdata/e2e/buildImage.sh

      - name: 🔐 Install cert-manager
        run: ./testdata/e2e/installCertManager.sh

      - name: 🔐 Install service certificate
        run: ./testdata/e2e/installCertificate.sh

      - name: 💉 Install Java Truststore Injection Webhook helm chart
        run: |
          ./testdata/e2e/installChart.sh
          kubectl create ns e2e-test

      - name: 🖥️ Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🛃 Test generated trust stores
        id: test_generated_stores
        run: ./testdata/e2e/testConfigMaps.sh
        continue-on-error: true

      - name: 📜 Print pod logs
        run: ./testdata/e2e/show-pod-logs.sh
        
      - name: ❌ Fail if 'Test generated trust stores' failed
        if: steps.test_generated_stores.outcome=='failure'
        run: |
          echo "Step 'Test generated trust stores' failed: Check 'Test generated trust storesr' and 'Print pod logs' as well as the job summary for errors"
          exit 1

  helm:
    name: Helm Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Set up Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: "go.mod"

      - name: Set up Tools
        run: make tb.semver tb.helm-docs

      - name: Lint
        run: |
          cp chart/README.md chart/README.md.old
          make helm-lint

      - name: Check chart/README.md is correctly generated with 'make docs'
        run: |
          # ignore version as it is updated during build
          sed -i '/!\[Version\:/d' chart/README.md
          sed -i '/!\[Version\:/d' chart/README.md.old
          sed -i -E 's/--version [0-9]+.[0-9]+.[0-9]+/--version x.x.x/' chart/README.md
          sed -i -E 's/--version [0-9]+.[0-9]+.[0-9]+/--version x.x.x/' chart/README.md.old
          diff chart/README.md.old chart/README.md

      - name: Template
        run: make helm-template
