name: docker-image

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: echo "curr_date=$(date --utc +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@96fe6ef7f33517b61c61be40b68a1882f3264fb8 # v4.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      - name: Login to ghcr.io
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push ${{github.event.release.tag_name }}
        id: docker_build_release
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        if: ${{ github.event.release.tag_name != '' }}
        with:
          push: true
          tags: ghcr.io/bakito/java-truststore-injection-webhook:latest,ghcr.io/bakito/java-truststore-injection-webhook:${{ github.event.release.tag_name }}
          platforms: linux/amd64
          provenance: false
          build-args: |
            VERSION=${{ github.event.release.tag_name }}
            BUILD=${{ env.curr_date }}

      - name: Build and push main
        id: docker_build_main
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        if: ${{ github.event.release.tag_name == '' }}
        with:
          push: true
          tags: ghcr.io/bakito/java-truststore-injection-webhook:main
          platforms: linux/amd64
          provenance: false
          build-args: |
            VERSION=main
            BUILD=${{ env.curr_date }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
